# The docker image to use to run the CI jobs.
# NOTE: Jobs must be tagged as `docker` to get picked up
#       by the CI docker runners.
image: "binaryanalysisplatform/bap:latest"

# JOB: run the tests for WP.
run_wp_tests:

  tags:
    - docker

  script:
    - apk add --update curl && rm -rf /var/cache/apk/*
    - make test -C wp
    - bash -x bin/integration-tests/run-tests.bash --report-results

# JOB: build BilDB.
build_bildb:

  tags:
    - docker

  script:
    - make -C bildb

