# The docker image to use to run the CI jobs.
# NOTE: Jobs must be tagged as `docker` to get picked up
#       by the CI docker runners.
image: "ocaml/opam:ubuntu-20.04-ocaml-4.14"

stages:
  - setup
  - builds

# JOB: install bap, etc.
setup:

  stage: setup

  tags:
    - docker

  script:
    - sudo -E apt update
    - sudo -E apt install -qq -yy
      zip binutils-multiarch clang debianutils libgmp-dev
      libncurses5-dev libzip-dev llvm-10-dev pkg-config zlib1g-dev
    - opam repo add opam https://opam.ocaml.org/
    - opam install core
    - opam repo add bap-testing
      git+https://github.com/BinaryAnalysisPlatform/opam-repository#testing
    - opam depext --install -y bap
    - which z3

# JOB: run the tests for WP.
run_wp_tests:

  stage: builds
  needs: ["setup"]

  tags:
    - docker

  script:
    - make test -C wp
    
# JOB: build BilDB.
build_bildb:

  stage: builds
  needs: ["setup"]

  tags:
    - docker

  script:
    - make -C bildb
