; ---------------------------------------------------------------------------
; Printing the command line arguments, one by one.
;
; To compile this:
;
;     nasm -f elf64 -o main.o main.asm
;     gcc -o main main.o
;
; To run it:
;
;     ./main
;

; Expose the following functions (include size for ELF symbol table):

        global show:function (show.end - show)
        global main:function (main.end - main)

; Import the following functions (to use below):

        extern printf
        extern puts

; ---------------------------------------------------------------------------
        SECTION .rodata
; ---------------------------------------------------------------------------

; A format string to print each command line argument.
fmt:    db `- %s\n`


; ---------------------------------------------------------------------------
        SECTION .text
; ---------------------------------------------------------------------------

show:
        mov     rsi, rdi
        mov     rdi, fmt
        call    printf
        ret
.end:

test:
        pop     rdi
        dec     rdi
        mov     rdi, 0
        mov     rsi, 0
        mov     rdi, 1
        dec     rdi
        mov     rax, [rdi + rsi]
        mov     rax, 60
        mov     rdi, 3
        syscall
        ret

then_case:
        mov     rdi, 10
        mov     rsi, 0
        mov     rax, 10
        ret

main:
        call    test
        push    rdi
        push    rsi
        mov     rdi, 0xffff
        shr     rdi, 5
        xor     rdi, 0xaaaa
        shl     rdi, 5
        xor     rdi, 0xaaaa
  	    and     rdi, 0x9999
        mov     rdi, 0xffff
        sub     rdi, 0xf000
        add     rdi, 0x1234
        shr     rdi, 5
        shl     rdi, 5
        xor     rdi, 0xaaaa
  	    and     rdi, 0x9999
        mov     rsi, 0xffff
        sub     rsi, 0xf000
        add     rsi, 0x1234
        shr     rsi, 5
        shl     rsi, 5
        xor     rsi, 0xaaaa
        and     rsi, 0x9999
        mov     rdi, 0xffff
        sub     rdi, 0xf000
        add     rdi, 0x1234
        shr     rdi, 5
        shl     rdi, 5
        xor     rdi, 0xaaaa
  	    and     rdi, 0x9999
        mov     rsi, 0xffff
        sub     rsi, 0xf000
        add     rsi, 0x1234
        shr     rsi, 5
        shl     rsi, 5
        xor     rsi, 0xaaaa
        and     rsi, 0x9999
        mov     rdi, 0xffff
        sub     rdi, 0xf000
        add     rdi, 0x1234
        shr     rdi, 5
        shl     rdi, 5
        xor     rdi, 0xaaaa
  	    and     rdi, 0x9999
        mov     rsi, 0xffff
        sub     rsi, 0xf000
        add     rsi, 0x1234
        shr     rsi, 5
        shl     rsi, 5
        xor     rsi, 0xaaaa
        and     rsi, 0x9999
        mov     rdi, 0xffff
        sub     rdi, 0xf000
        add     rdi, 0x1234
        shr     rdi, 5
        shl     rdi, 5
        xor     rdi, 0xaaaa
  	    and     rdi, 0x9999
        mov     rsi, 0xffff
        sub     rsi, 0xf000
        add     rsi, 0x1234
        shr     rsi, 5
        shl     rsi, 5
        xor     rsi, 0xaaaa
        and     rsi, 0x9999
        mov     rdi, 0xffff
        sub     rdi, 0xf000
        add     rdi, 0x1234
        shr     rdi, 5
        shl     rdi, 5
        xor     rdi, 0xaaaa
  	    and     rdi, 0x9999
        mov     rsi, 0xffff
        sub     rsi, 0xf000
        add     rsi, 0x1234
        shr     rsi, 5
        shl     rsi, 5
        xor     rsi, 0xaaaa
        and     rsi, 0x9999
        mov     rdi, 0xffff
        sub     rdi, 0xf000
        add     rdi, 0x1234
        shr     rdi, 5
        shl     rdi, 5
        xor     rdi, 0xaaaa
  	    and     rdi, 0x9999
        mov     rsi, 0xffff
        sub     rsi, 0xf000
        add     rsi, 0x1234
        shr     rsi, 5
        shl     rsi, 5
        xor     rsi, 0xaaaa
        and     rsi, 0x9999
        mov     rdi, 0xffff
        sub     rdi, 0xf000
        add     rdi, 0x1234
        shr     rdi, 5
        shl     rdi, 5
        xor     rdi, 0xaaaa
  	    and     rdi, 0x9999
        mov     rsi, 0xffff
        sub     rsi, 0xf000
        add     rsi, 0x1234
        shr     rsi, 5
        shl     rsi, 5
        xor     rsi, 0xaaaa
        and     rsi, 0x9999
        mov     rdi, 0xffff
        sub     rdi, 0xf000
        add     rdi, 0x1234
        shr     rdi, 5
        shl     rdi, 5
        xor     rdi, 0xaaaa
  	    and     rdi, 0x9999
        mov     rsi, 0xffff
        sub     rsi, 0xf000
        add     rsi, 0x1234
        shr     rsi, 5
        shl     rsi, 5
        xor     rsi, 0xaaaa
        and     rsi, 0x9999
        mov     rdi, 0xffff
        sub     rdi, 0xf000
        add     rdi, 0x1234
        shr     rdi, 5
        shl     rdi, 5
        xor     rdi, 0xaaaa
  	    and     rdi, 0x9999
        mov     rsi, 0xffff
        sub     rsi, 0xf000
        add     rsi, 0x1234
        shr     rsi, 5
        shl     rsi, 5
        xor     rsi, 0xaaaa
        and     rsi, 0x9999
        mov     rdi, 0xffff
        sub     rdi, 0xf000
        add     rdi, 0x1234
        shr     rdi, 5
        shl     rdi, 5
        xor     rdi, 0xaaaa
  	    and     rdi, 0x9999
        mov     rsi, 0xffff
        sub     rsi, 0xf000
        add     rsi, 0x1234
        shr     rsi, 5
        shl     rsi, 5
        xor     rsi, 0xaaaa
        and     rsi, 0x9999
        mov     rdi, 0xffff
        sub     rdi, 0xf000
        add     rdi, 0x1234
        shr     rdi, 5
        shl     rdi, 5
        xor     rdi, 0xaaaa
  	    and     rdi, 0x9999
        mov     rsi, 0xffff
        sub     rsi, 0xf000
        add     rsi, 0x1234
        shr     rsi, 5
        shl     rsi, 5
        xor     rsi, 0xaaaa
        and     rsi, 0x9999
        mov     rdi, 0xffff
        sub     rdi, 0xf000
        add     rdi, 0x1234
        shr     rdi, 5
        shl     rdi, 5
        xor     rdi, 0xaaaa
  	    and     rdi, 0x9999
        mov     rsi, 0xffff
        sub     rsi, 0xf000
        add     rsi, 0x1234
        shr     rsi, 5
        shl     rsi, 5
        xor     rsi, 0xaaaa
        and     rsi, 0x9999
        mov     rdi, 0xffff
        sub     rdi, 0xf000
        add     rdi, 0x1234
        shr     rdi, 5
        shl     rdi, 5
        xor     rdi, 0xaaaa
  	    and     rdi, 0x9999
        mov     rsi, 0xffff
        sub     rsi, 0xf000
        add     rsi, 0x1234
        shr     rsi, 5
        shl     rsi, 5
        xor     rsi, 0xaaaa
        and     rsi, 0x9999
        mov     rdi, 0xffff
        sub     rdi, 0xf000
        add     rdi, 0x1234
        shr     rdi, 5
        shl     rdi, 5
        xor     rdi, 0xaaaa
  	    and     rdi, 0x9999
        mov     rsi, 0xffff
        sub     rsi, 0xf000
        add     rsi, 0x1234
        shr     rsi, 5
        shl     rsi, 5
        xor     rsi, 0xaaaa
        and     rsi, 0x9999
        mov     rdi, 0xffff
        sub     rdi, 0xf000
        add     rdi, 0x1234
        shr     rdi, 5
        shl     rdi, 5
        xor     rdi, 0xaaaa
  	    and     rdi, 0x9999
        mov     rsi, 0xffff
        sub     rsi, 0xf000
        add     rsi, 0x1234
        shr     rsi, 5
        shl     rsi, 5
        xor     rsi, 0xaaaa
        and     rsi, 0x9999
        mov     rdi, 0xffff
        sub     rdi, 0xf000
        add     rdi, 0x1234
        shr     rdi, 5
        shl     rdi, 5
        xor     rdi, 0xaaaa
  	    and     rdi, 0x9999
        mov     rsi, 0xffff
        sub     rsi, 0xf000
        add     rsi, 0x1234
        shr     rsi, 5
        shl     rsi, 5
        xor     rsi, 0xaaaa
        and     rsi, 0x9999
        mov     rdi, 0xffff
        sub     rdi, 0xf000
        add     rdi, 0x1234
        shr     rdi, 5
        shl     rdi, 5
        xor     rdi, 0xaaaa
  	    and     rdi, 0x9999
        mov     rsi, 0xffff
        sub     rsi, 0xf000
        add     rsi, 0x1234
        shr     rsi, 5
        shl     rsi, 5
        xor     rsi, 0xaaaa
        and     rsi, 0x9999
        mov     rdi, 0xffff
        sub     rdi, 0xf000
        add     rdi, 0x1234
        shr     rdi, 5
        shl     rdi, 5
        xor     rdi, 0xaaaa
  	    and     rdi, 0x9999
        mov     rsi, 0xffff
        sub     rsi, 0xf000
        add     rsi, 0x1234
        shr     rsi, 5
        shl     rsi, 5
        xor     rsi, 0xaaaa
        and     rsi, 0x9999
        mov     rdi, 0xffff
        sub     rdi, 0xf000
        add     rdi, 0x1234
        shr     rdi, 5
        shl     rdi, 5
        xor     rdi, 0xaaaa
  	    and     rdi, 0x9999
        mov     rsi, 0xffff
        sub     rsi, 0xf000
        add     rsi, 0x1234
        shr     rsi, 5
        shl     rsi, 5
        xor     rsi, 0xaaaa
        and     rsi, 0x9999
        mov     rdi, 0xffff
        sub     rdi, 0xf000
        add     rdi, 0x1234
        shr     rdi, 5
        shl     rdi, 5
        xor     rdi, 0xaaaa
  	    and     rdi, 0x9999
        mov     rsi, 0xffff
        sub     rsi, 0xf000
        add     rsi, 0x1234
        shr     rsi, 5
        shl     rsi, 5
        xor     rsi, 0xaaaa
        and     rsi, 0x9999
        mov     rdi, 0xffff
        sub     rdi, 0xf000
        add     rdi, 0x1234
        shr     rdi, 5
        shl     rdi, 5
        xor     rdi, 0xaaaa
  	    and     rdi, 0x9999
        mov     rsi, 0xffff
        sub     rsi, 0xf000
        add     rsi, 0x1234
        shr     rsi, 5
        shl     rsi, 5
        xor     rsi, 0xaaaa
        and     rsi, 0x9999
        mov     rdi, 0xffff
        sub     rdi, 0xf000
        add     rdi, 0x1234
        shr     rdi, 5
        shl     rdi, 5
        xor     rdi, 0xaaaa
  	    and     rdi, 0x9999
        mov     rsi, 0xffff
        sub     rsi, 0xf000
        add     rsi, 0x1234
        shr     rsi, 5
        shl     rsi, 5
        xor     rsi, 0xaaaa
        and     rsi, 0x9999
        mov     rdi, 0xffff
        sub     rdi, 0xf000
        add     rdi, 0x1234
        shr     rdi, 5
        shl     rdi, 5
        xor     rdi, 0xaaaa
  	    and     rdi, 0x9999
        mov     rsi, 0xffff
        sub     rsi, 0xf000
        add     rsi, 0x1234
        shr     rsi, 5
        shl     rsi, 5
        xor     rsi, 0xaaaa
        and     rsi, 0x9999
        mov     rdi, 0xffff
        sub     rdi, 0xf000
        add     rdi, 0x1234
        shr     rdi, 5
        shl     rdi, 5
        xor     rdi, 0xaaaa
  	    and     rdi, 0x9999
        mov     rsi, 0xffff
        sub     rsi, 0xf000
        add     rsi, 0x1234
        shr     rsi, 5
        shl     rsi, 5
        xor     rsi, 0xaaaa
        and     rsi, 0x9999
        mov     rdi, 0xffff
        sub     rdi, 0xf000
        add     rdi, 0x1234
        shr     rdi, 5
        shl     rdi, 5
        xor     rdi, 0xaaaa
  	    and     rdi, 0x9999
        mov     rsi, 0xffff
        sub     rsi, 0xf000
        add     rsi, 0x1234
        shr     rsi, 5
        shl     rsi, 5
        xor     rsi, 0xaaaa
        and     rsi, 0x9999
        mov     rdi, 0xffff
        sub     rdi, 0xf000
        add     rdi, 0x1234
        shr     rdi, 5
        shl     rdi, 5
        xor     rdi, 0xaaaa
  	    and     rdi, 0x9999
        mov     rsi, 0xffff
        sub     rsi, 0xf000
        add     rsi, 0x1234
        shr     rsi, 5
        shl     rsi, 5
        xor     rsi, 0xaaaa
        and     rsi, 0x9999
        mov     rdi, 0xffff
        sub     rdi, 0xf000
        add     rdi, 0x1234
        shr     rdi, 5
        shl     rdi, 5
        xor     rdi, 0xaaaa
  	    and     rdi, 0x9999
        mov     rsi, 0xffff
        sub     rsi, 0xf000
        add     rsi, 0x1234
        shr     rsi, 5
        shl     rsi, 5
        xor     rsi, 0xaaaa
        and     rsi, 0x9999
        mov     rdi, 0xffff
        sub     rdi, 0xf000
        add     rdi, 0x1234
        shr     rdi, 5
        shl     rdi, 5
        xor     rdi, 0xaaaa
  	    and     rdi, 0x9999
        mov     rsi, 0xffff
        sub     rsi, 0xf000
        add     rsi, 0x1234
        shr     rsi, 5
        shl     rsi, 5
        xor     rsi, 0xaaaa
        and     rsi, 0x9999
        mov     rdi, 0xffff
        sub     rdi, 0xf000
        add     rdi, 0x1234
        shr     rdi, 5
        shl     rdi, 5
        xor     rdi, 0xaaaa
  	    and     rdi, 0x9999
        mov     rsi, 0xffff
        sub     rsi, 0xf000
        add     rsi, 0x1234
        shr     rsi, 5
        shl     rsi, 5
        xor     rsi, 0xaaaa
        and     rsi, 0x9999
        mov     rdi, 0xffff
        sub     rdi, 0xf000
        add     rdi, 0x1234
        shr     rdi, 5
        shl     rdi, 5
        xor     rdi, 0xaaaa
  	    and     rdi, 0x9999
        mov     rsi, 0xffff
        sub     rsi, 0xf000
        add     rsi, 0x1234
        shr     rsi, 5
        shl     rsi, 5
        xor     rsi, 0xaaaa
        and     rsi, 0x9999
        mov     rdi, 0xffff
        sub     rdi, 0xf000
        add     rdi, 0x1234
        shr     rdi, 5
        shl     rdi, 5
        xor     rdi, 0xaaaa
  	    and     rdi, 0x9999
        mov     rsi, 0xffff
        sub     rsi, 0xf000
        add     rsi, 0x1234
        shr     rsi, 5
        shl     rsi, 5
        xor     rsi, 0xaaaa
        and     rsi, 0x9999
        mov     rdi, 0xffff
        sub     rdi, 0xf000
        add     rdi, 0x1234
        shr     rdi, 5
        shl     rdi, 5
        xor     rdi, 0xaaaa
  	    and     rdi, 0x9999
        mov     rsi, 0xffff
        sub     rsi, 0xf000
        add     rsi, 0x1234
        shr     rsi, 5
        shl     rsi, 5
        xor     rsi, 0xaaaa
        and     rsi, 0x9999
        mov     rdi, 0xffff
        sub     rdi, 0xf000
        add     rdi, 0x1234
        shr     rdi, 5
        shl     rdi, 5
        xor     rdi, 0xaaaa
  	    and     rdi, 0x9999
        mov     rsi, 0xffff
        sub     rsi, 0xf000
        add     rsi, 0x1234
        shr     rsi, 5
        shl     rsi, 5
        xor     rsi, 0xaaaa
        and     rsi, 0x9999
        mov     rdi, 0xffff
        sub     rdi, 0xf000
        add     rdi, 0x1234
        shr     rdi, 5
        shl     rdi, 5
        xor     rdi, 0xaaaa
  	    and     rdi, 0x9999
        mov     rsi, 0xffff
        sub     rsi, 0xf000
        add     rsi, 0x1234
        shr     rsi, 5
        shl     rsi, 5
        xor     rsi, 0xaaaa
        and     rsi, 0x9999
        mov     rdi, 0xffff
        sub     rdi, 0xf000
        add     rdi, 0x1234
        shr     rdi, 5
        shl     rdi, 5
        xor     rdi, 0xaaaa
  	    and     rdi, 0x9999
        mov     rsi, 0xffff
        sub     rsi, 0xf000
        add     rsi, 0x1234
        shr     rsi, 5
        shl     rsi, 5
        xor     rsi, 0xaaaa
        and     rsi, 0x9999
        mov     rdi, 0xffff
        sub     rdi, 0xf000
        add     rdi, 0x1234
        shr     rdi, 5
        shl     rdi, 5
        xor     rdi, 0xaaaa
  	    and     rdi, 0x9999
        mov     rsi, 0xffff
        sub     rsi, 0xf000
        add     rsi, 0x1234
        shr     rsi, 5
        shl     rsi, 5
        xor     rsi, 0xaaaa
        and     rsi, 0x9999
        mov     rdi, 0xffff
        sub     rdi, 0xf000
        add     rdi, 0x1234
        shr     rdi, 5
        shl     rdi, 5
        xor     rdi, 0xaaaa
  	    and     rdi, 0x9999
        mov     rsi, 0xffff
        sub     rsi, 0xf000
        add     rsi, 0x1234
        shr     rsi, 5
        shl     rsi, 5
        xor     rsi, 0xaaaa
        and     rsi, 0x9999
        mov     rdi, 0xffff
        sub     rdi, 0xf000
        add     rdi, 0x1234
        shr     rdi, 5
        shl     rdi, 5
        xor     rdi, 0xaaaa
  	    and     rdi, 0x9999
        mov     rsi, 0xffff
        sub     rsi, 0xf000
        add     rsi, 0x1234
        shr     rsi, 5
        shl     rsi, 5
        xor     rsi, 0xaaaa
        and     rsi, 0x9999
        mov     rdi, 0xffff
        sub     rdi, 0xf000
        add     rdi, 0x1234
        shr     rdi, 5
        shl     rdi, 5
        xor     rdi, 0xaaaa
  	    and     rdi, 0x9999
        mov     rsi, 0xffff
        sub     rsi, 0xf000
        add     rsi, 0x1234
        shr     rsi, 5
        shl     rsi, 5
        xor     rsi, 0xaaaa
        and     rsi, 0x9999
        mov     rdi, 0xffff
        sub     rdi, 0xf000
        add     rdi, 0x1234
        shr     rdi, 5
        shl     rdi, 5
        xor     rdi, 0xaaaa
  	    and     rdi, 0x9999
        mov     rsi, 0xffff
        sub     rsi, 0xf000
        add     rsi, 0x1234
        shr     rsi, 5
        shl     rsi, 5
        xor     rsi, 0xaaaa
        and     rsi, 0x9999
        mov     rdi, 0xffff
        sub     rdi, 0xf000
        add     rdi, 0x1234
        shr     rdi, 5
        shl     rdi, 5
        xor     rdi, 0xaaaa
  	    and     rdi, 0x9999
        mov     rsi, 0xffff
        sub     rsi, 0xf000
        add     rsi, 0x1234
        shr     rsi, 5
        shl     rsi, 5
        xor     rsi, 0xaaaa
        and     rsi, 0x9999
        mov     rdi, 0xffff
        sub     rdi, 0xf000
        add     rdi, 0x1234
        shr     rdi, 5
        shl     rdi, 5
        xor     rdi, 0xaaaa
  	    and     rdi, 0x9999
        mov     rsi, 0xffff
        sub     rsi, 0xf000
        add     rsi, 0x1234
        shr     rsi, 5
        shl     rsi, 5
        xor     rsi, 0xaaaa
        and     rsi, 0x9999
        mov     rdi, 0xffff
        sub     rdi, 0xf000
        add     rdi, 0x1234
        shr     rdi, 5
        shl     rdi, 5
        xor     rdi, 0xaaaa
  	    and     rdi, 0x9999
        mov     rsi, 0xffff
        sub     rsi, 0xf000
        add     rsi, 0x1234
        shr     rsi, 5
        shl     rsi, 5
        xor     rsi, 0xaaaa
        and     rsi, 0x9999
        mov     rdi, 0xffff
        sub     rdi, 0xf000
        add     rdi, 0x1234
        shr     rdi, 5
        shl     rdi, 5
        xor     rdi, 0xaaaa
  	    and     rdi, 0x9999
        mov     rsi, 0xffff
        sub     rsi, 0xf000
        add     rsi, 0x1234
        shr     rsi, 5
        shl     rsi, 5
        xor     rsi, 0xaaaa
        and     rsi, 0x9999
        mov     rdi, 0xffff
        sub     rdi, 0xf000
        add     rdi, 0x1234
        shr     rdi, 5
        shl     rdi, 5
        xor     rdi, 0xaaaa
  	    and     rdi, 0x9999
        mov     rsi, 0xffff
        sub     rsi, 0xf000
        add     rsi, 0x1234
        shr     rsi, 5
        shl     rsi, 5
        xor     rsi, 0xaaaa
        and     rsi, 0x9999
        mov     rdi, 0xffff
        sub     rdi, 0xf000
        add     rdi, 0x1234
        shr     rdi, 5
        shl     rdi, 5
        xor     rdi, 0xaaaa
  	    and     rdi, 0x9999
        mov     rsi, 0xffff
        sub     rsi, 0xf000
        add     rsi, 0x1234
        shr     rsi, 5
        shl     rsi, 5
        xor     rsi, 0xaaaa
        and     rsi, 0x9999
        mov     rdi, 0xffff
        sub     rdi, 0xf000
        add     rdi, 0x1234
        shr     rdi, 5
        shl     rdi, 5
        xor     rdi, 0xaaaa
  	    and     rdi, 0x9999
        mov     rsi, 0xffff
        sub     rsi, 0xf000
        add     rsi, 0x1234
        shr     rsi, 5
        shl     rsi, 5
        xor     rsi, 0xaaaa
        and     rsi, 0x9999
        mov     rdi, 0xffff
        sub     rdi, 0xf000
        add     rdi, 0x1234
        shr     rdi, 5
        shl     rdi, 5
        xor     rdi, 0xaaaa
  	    and     rdi, 0x9999
        mov     rsi, 0xffff
        sub     rsi, 0xf000
        add     rsi, 0x1234
        shr     rsi, 5
        shl     rsi, 5
        xor     rsi, 0xaaaa
        and     rsi, 0x9999
        mov     rdi, 0xffff
        sub     rdi, 0xf000
        add     rdi, 0x1234
        shr     rdi, 5
        shl     rdi, 5
        xor     rdi, 0xaaaa
  	    and     rdi, 0x9999
        mov     rsi, 0xffff
        sub     rsi, 0xf000
        add     rsi, 0x1234
        shr     rsi, 5
        shl     rsi, 5
        xor     rsi, 0xaaaa
        and     rsi, 0x9999
        mov     rdi, 0xffff
        sub     rdi, 0xf000
        add     rdi, 0x1234
        shr     rdi, 5
        shl     rdi, 5
        xor     rdi, 0xaaaa
  	    and     rdi, 0x9999
        mov     rsi, 0xffff
        sub     rsi, 0xf000
        add     rsi, 0x1234
        shr     rsi, 5
        shl     rsi, 5
        xor     rsi, 0xaaaa
        and     rsi, 0x9999
        mov     rdi, 0xffff
        sub     rdi, 0xf000
        add     rdi, 0x1234
        shr     rdi, 5
        shl     rdi, 5
        xor     rdi, 0xaaaa
  	    and     rdi, 0x9999
        mov     rsi, 0xffff
        sub     rsi, 0xf000
        add     rsi, 0x1234
        shr     rsi, 5
        shl     rsi, 5
        xor     rsi, 0xaaaa
        and     rsi, 0x9999
        mov     rdi, 0xffff
        sub     rdi, 0xf000
        add     rdi, 0x1234
        shr     rdi, 5
        shl     rdi, 5
        xor     rdi, 0xaaaa
  	    and     rdi, 0x9999
        mov     rsi, 0xffff
        sub     rsi, 0xf000
        add     rsi, 0x1234
        shr     rsi, 5
        shl     rsi, 5
        xor     rsi, 0xaaaa
        and     rsi, 0x9999
        mov     rdi, 0xffff
        sub     rdi, 0xf000
        add     rdi, 0x1234
        shr     rdi, 5
        shl     rdi, 5
        xor     rdi, 0xaaaa
  	    and     rdi, 0x9999
        mov     rsi, 0xffff
        sub     rsi, 0xf000
        add     rsi, 0x1234
        shr     rsi, 5
        shl     rsi, 5
        xor     rsi, 0xaaaa
        and     rsi, 0x9999
        mov     rdi, 0xffff
        sub     rdi, 0xf000
        add     rdi, 0x1234
        shr     rdi, 5
        shl     rdi, 5
        xor     rdi, 0xaaaa
  	    and     rdi, 0x9999
        mov     rsi, 0xffff
        sub     rsi, 0xf000
        add     rsi, 0x1234
        shr     rsi, 5
        shl     rsi, 5
        xor     rsi, 0xaaaa
        and     rsi, 0x9999
        mov     rdi, 0xffff
        sub     rdi, 0xf000
        add     rdi, 0x1234
        shr     rdi, 5
        shl     rdi, 5
        xor     rdi, 0xaaaa
  	    and     rdi, 0x9999
        mov     rsi, 0xffff
        sub     rsi, 0xf000
        add     rsi, 0x1234
        shr     rsi, 5
        shl     rsi, 5
        xor     rsi, 0xaaaa
        and     rsi, 0x9999
        mov     rdi, 0xffff
        sub     rdi, 0xf000
        add     rdi, 0x1234
        shr     rdi, 5
        shl     rdi, 5
        xor     rdi, 0xaaaa
  	    and     rdi, 0x9999
        mov     rsi, 0xffff
        sub     rsi, 0xf000
        add     rsi, 0x1234
        shr     rsi, 5
        shl     rsi, 5
        xor     rsi, 0xaaaa
        and     rsi, 0x9999
        mov     rdi, 0xffff
        sub     rdi, 0xf000
        add     rdi, 0x1234
        shr     rdi, 5
        shl     rdi, 5
        xor     rdi, 0xaaaa
  	    and     rdi, 0x9999
        mov     rsi, 0xffff
        sub     rsi, 0xf000
        add     rsi, 0x1234
        shr     rsi, 5
        shl     rsi, 5
        xor     rsi, 0xaaaa
        and     rsi, 0x9999
        mov     rdi, 0xffff
        sub     rdi, 0xf000
        add     rdi, 0x1234
        shr     rdi, 5
        shl     rdi, 5
        xor     rdi, 0xaaaa
  	    and     rdi, 0x9999
        mov     rsi, 0xffff
        sub     rsi, 0xf000
        add     rsi, 0x1234
        shr     rsi, 5
        shl     rsi, 5
        xor     rsi, 0xaaaa
        and     rsi, 0x9999
        mov     rdi, 0xffff
        sub     rdi, 0xf000
        add     rdi, 0x1234
        shr     rdi, 5
        shl     rdi, 5
        xor     rdi, 0xaaaa
  	    and     rdi, 0x9999
        mov     rsi, 0xffff
        sub     rsi, 0xf000
        add     rsi, 0x1234
        shr     rsi, 5
        shl     rsi, 5
        xor     rsi, 0xaaaa
        and     rsi, 0x9999
        mov     rdi, 0xffff
        sub     rdi, 0xf000
        add     rdi, 0x1234
        shr     rdi, 5
        shl     rdi, 5
        xor     rdi, 0xaaaa
  	    and     rdi, 0x9999
        mov     rsi, 0xffff
        sub     rsi, 0xf000
        add     rsi, 0x1234
        shr     rsi, 5
        shl     rsi, 5
        xor     rsi, 0xaaaa
        and     rsi, 0x9999
        mov     rdi, 0xffff
        sub     rdi, 0xf000
        add     rdi, 0x1234
        shr     rdi, 5
        shl     rdi, 5
        xor     rdi, 0xaaaa
  	    and     rdi, 0x9999
        mov     rsi, 0xffff
        sub     rsi, 0xf000
        add     rsi, 0x1234
        shr     rsi, 5
        shl     rsi, 5
        xor     rsi, 0xaaaa
        and     rsi, 0x9999
        mov     rdi, 0xffff
        sub     rdi, 0xf000
        add     rdi, 0x1234
        shr     rdi, 5
        shl     rdi, 5
        xor     rdi, 0xaaaa
  	    and     rdi, 0x9999
        mov     rsi, 0xffff
        sub     rsi, 0xf000
        add     rsi, 0x1234
        shr     rsi, 5
        shl     rsi, 5
        xor     rsi, 0xaaaa
        and     rsi, 0x9999
        mov     rdi, 0xffff
        sub     rdi, 0xf000
        add     rdi, 0x1234
        shr     rdi, 5
        shl     rdi, 5
        xor     rdi, 0xaaaa
  	    and     rdi, 0x9999
        mov     rsi, 0xffff
        sub     rsi, 0xf000
        add     rsi, 0x1234
        shr     rsi, 5
        shl     rsi, 5
        xor     rsi, 0xaaaa
        and     rsi, 0x9999
        mov     rdi, 0xffff
        sub     rdi, 0xf000
        add     rdi, 0x1234
        shr     rdi, 5
        shl     rdi, 5
        xor     rdi, 0xaaaa
  	    and     rdi, 0x9999
        mov     rsi, 0xffff
        sub     rsi, 0xf000
        add     rsi, 0x1234
        shr     rsi, 5
        shl     rsi, 5
        xor     rsi, 0xaaaa
        and     rsi, 0x9999
        mov     rdi, 0xffff
        sub     rdi, 0xf000
        add     rdi, 0x1234
        shr     rdi, 5
        shl     rdi, 5
        xor     rdi, 0xaaaa
  	    and     rdi, 0x9999
        mov     rsi, 0xffff
        sub     rsi, 0xf000
        add     rsi, 0x1234
        shr     rsi, 5
        shl     rsi, 5
        xor     rsi, 0xaaaa
        and     rsi, 0x9999
        mov     rdi, 0xffff
        sub     rdi, 0xf000
        add     rdi, 0x1234
        shr     rdi, 5
        shl     rdi, 5
        xor     rdi, 0xaaaa
  	    and     rdi, 0x9999
        mov     rsi, 0xffff
        sub     rsi, 0xf000
        add     rsi, 0x1234
        shr     rsi, 5
        shl     rsi, 5
        xor     rsi, 0xaaaa
        and     rsi, 0x9999
        mov     rdi, 0xffff
        sub     rdi, 0xf000
        add     rdi, 0x1234
        shr     rdi, 5
        shl     rdi, 5
        xor     rdi, 0xaaaa
  	    and     rdi, 0x9999
        mov     rsi, 0xffff
        sub     rsi, 0xf000
        add     rsi, 0x1234
        shr     rsi, 5
        shl     rsi, 5
        xor     rsi, 0xaaaa
        and     rsi, 0x9999
        mov     rdi, 0xffff
        sub     rdi, 0xf000
        add     rdi, 0x1234
        shr     rdi, 5
        shl     rdi, 5
        xor     rdi, 0xaaaa
  	    and     rdi, 0x9999
        mov     rsi, 0xffff
        sub     rsi, 0xf000
        add     rsi, 0x1234
        shr     rsi, 5
        shl     rsi, 5
        xor     rsi, 0xaaaa
        and     rsi, 0x9999
        mov     rdi, 0xffff
        sub     rdi, 0xf000
        add     rdi, 0x1234
        shr     rdi, 5
        shl     rdi, 5
        xor     rdi, 0xaaaa
  	    and     rdi, 0x9999
        mov     rsi, 0xffff
        sub     rsi, 0xf000
        add     rsi, 0x1234
        shr     rsi, 5
        shl     rsi, 5
        xor     rsi, 0xaaaa
        and     rsi, 0x9999
        mov     rdi, 0xffff
        sub     rdi, 0xf000
        add     rdi, 0x1234
        shr     rdi, 5
        shl     rdi, 5
        xor     rdi, 0xaaaa
  	    and     rdi, 0x9999
        mov     rsi, 0xffff
        sub     rsi, 0xf000
        add     rsi, 0x1234
        shr     rsi, 5
        shl     rsi, 5
        xor     rsi, 0xaaaa
        and     rsi, 0x9999
        mov     rdi, 0xffff
        sub     rdi, 0xf000
        add     rdi, 0x1234
        shr     rdi, 5
        shl     rdi, 5
        xor     rdi, 0xaaaa
  	    and     rdi, 0x9999
        mov     rsi, 0xffff
        sub     rsi, 0xf000
        add     rsi, 0x1234
        shr     rsi, 5
        shl     rsi, 5
        xor     rsi, 0xaaaa
        and     rsi, 0x9999
        mov     rdi, 0xffff
        sub     rdi, 0xf000
        add     rdi, 0x1234
        shr     rdi, 5
        shl     rdi, 5
        xor     rdi, 0xaaaa
  	    and     rdi, 0x9999
        mov     rsi, 0xffff
        sub     rsi, 0xf000
        add     rsi, 0x1234
        shr     rsi, 5
        shl     rsi, 5
        xor     rsi, 0xaaaa
        and     rsi, 0x9999
        mov     rdi, 0xffff
        sub     rdi, 0xf000
        add     rdi, 0x1234
        shr     rdi, 5
        shl     rdi, 5
        xor     rdi, 0xaaaa
  	    and     rdi, 0x9999
        mov     rsi, 0xffff
        sub     rsi, 0xf000
        add     rsi, 0x1234
        shr     rsi, 5
        shl     rsi, 5
        xor     rsi, 0xaaaa
        and     rsi, 0x9999
        mov     rdi, 0xffff
        sub     rdi, 0xf000
        add     rdi, 0x1234
        shr     rdi, 5
        shl     rdi, 5
        xor     rdi, 0xaaaa
  	    and     rdi, 0x9999
        mov     rsi, 0xffff
        sub     rsi, 0xf000
        add     rsi, 0x1234
        shr     rsi, 5
        shl     rsi, 5
        xor     rsi, 0xaaaa
        and     rsi, 0x9999
        mov     rdi, 0xffff
        sub     rdi, 0xf000
        add     rdi, 0x1234
        shr     rdi, 5
        shl     rdi, 5
        xor     rdi, 0xaaaa
  	    and     rdi, 0x9999
        mov     rsi, 0xffff
        sub     rsi, 0xf000
        add     rsi, 0x1234
        shr     rsi, 5
        shl     rsi, 5
        xor     rsi, 0xaaaa
        and     rsi, 0x9999
        mov     rdi, 0xffff
        sub     rdi, 0xf000
        add     rdi, 0x1234
        shr     rdi, 5
        shl     rdi, 5
        xor     rdi, 0xaaaa
  	    and     rdi, 0x9999
        mov     rsi, 0xffff
        sub     rsi, 0xf000
        add     rsi, 0x1234
        shr     rsi, 5
        shl     rsi, 5
        xor     rsi, 0xaaaa
        and     rsi, 0x9999
        mov     rdi, 0xffff
        sub     rdi, 0xf000
        add     rdi, 0x1234
        shr     rdi, 5
        shl     rdi, 5
        xor     rdi, 0xaaaa
  	    and     rdi, 0x9999
        mov     rsi, 0xffff
        sub     rsi, 0xf000
        add     rsi, 0x1234
        shr     rsi, 5
        shl     rsi, 5
        xor     rsi, 0xaaaa
        and     rsi, 0x9999
        mov     rdi, 0xffff
        sub     rdi, 0xf000
        add     rdi, 0x1234
        shr     rdi, 5
        shl     rdi, 5
        xor     rdi, 0xaaaa
  	    and     rdi, 0x9999
        mov     rsi, 0xffff
        sub     rsi, 0xf000
        add     rsi, 0x1234
        shr     rsi, 5
        shl     rsi, 5
        xor     rsi, 0xaaaa
        and     rsi, 0x9999
        mov     rdi, 0xffff
        sub     rdi, 0xf000
        add     rdi, 0x1234
        shr     rdi, 5
        shl     rdi, 5
        xor     rdi, 0xaaaa
  	    and     rdi, 0x9999
        mov     rsi, 0xffff
        sub     rsi, 0xf000
        add     rsi, 0x1234
        shr     rsi, 5
        shl     rsi, 5
        xor     rsi, 0xaaaa
        and     rsi, 0x9999
        mov     rdi, 0xffff
        sub     rdi, 0xf000
        add     rdi, 0x1234
        shr     rdi, 5
        shl     rdi, 5
        xor     rdi, 0xaaaa
  	    and     rdi, 0x9999
        mov     rsi, 0xffff
        sub     rsi, 0xf000
        add     rsi, 0x1234
        shr     rsi, 5
        shl     rsi, 5
        xor     rsi, 0xaaaa
        and     rsi, 0x9999
        mov     rdi, 0xffff
        sub     rdi, 0xf000
        add     rdi, 0x1234
        shr     rdi, 5
        shl     rdi, 5
        xor     rdi, 0xaaaa
  	    and     rdi, 0x9999
        mov     rsi, 0xffff
        sub     rsi, 0xf000
        add     rsi, 0x1234
        shr     rsi, 5
        shl     rsi, 5
        xor     rsi, 0xaaaa
        and     rsi, 0x9999
        mov     rdi, 0xffff
        sub     rdi, 0xf000
        add     rdi, 0x1234
        shr     rdi, 5
        shl     rdi, 5
        xor     rdi, 0xaaaa
  	    and     rdi, 0x9999
        mov     rsi, 0xffff
        sub     rsi, 0xf000
        add     rsi, 0x1234
        shr     rsi, 5
        shl     rsi, 5
        xor     rsi, 0xaaaa
        and     rsi, 0x9999
        mov     rdi, 0xffff
        sub     rdi, 0xf000
        add     rdi, 0x1234
        shr     rdi, 5
        shl     rdi, 5
        xor     rdi, 0xaaaa
  	    and     rdi, 0x9999
        mov     rsi, 0xffff
        sub     rsi, 0xf000
        add     rsi, 0x1234
        shr     rsi, 5
        shl     rsi, 5
        xor     rsi, 0xaaaa
        and     rsi, 0x9999
        mov     rdi, 0xffff
        sub     rdi, 0xf000
        add     rdi, 0x1234
        shr     rdi, 5
        shl     rdi, 5
        xor     rdi, 0xaaaa
  	    and     rdi, 0x9999
        mov     rsi, 0xffff
        sub     rsi, 0xf000
        add     rsi, 0x1234
        shr     rsi, 5
        shl     rsi, 5
        xor     rsi, 0xaaaa
        and     rsi, 0x9999
        mov     rdi, 0xffff
        sub     rdi, 0xf000
        add     rdi, 0x1234
        shr     rdi, 5
        shl     rdi, 5
        xor     rdi, 0xaaaa
  	    and     rdi, 0x9999
        mov     rsi, 0xffff
        sub     rsi, 0xf000
        add     rsi, 0x1234
        shr     rsi, 5
        shl     rsi, 5
        xor     rsi, 0xaaaa
        and     rsi, 0x9999
        mov     rdi, 0xffff
        sub     rdi, 0xf000
        add     rdi, 0x1234
        shr     rdi, 5
        shl     rdi, 5
        xor     rdi, 0xaaaa
  	    and     rdi, 0x9999
        mov     rsi, 0xffff
        sub     rsi, 0xf000
        add     rsi, 0x1234
        shr     rsi, 5
        shl     rsi, 5
        xor     rsi, 0xaaaa
        and     rsi, 0x9999
        mov     rdi, 0xffff
        sub     rdi, 0xf000
        add     rdi, 0x1234
        shr     rdi, 5
        shl     rdi, 5
        xor     rdi, 0xaaaa
  	    and     rdi, 0x9999
        mov     rdi, 0xffff
        sub     rdi, 0xf000
        add     rdi, 0x1234
        shr     rdi, 5
        shl     rdi, 5
        xor     rdi, 0xaaaa
  	    and     rdi, 0x9999
        mov     rdi, 0xffff
        sub     rdi, 0xf000
        add     rdi, 0x1234
        shr     rdi, 5
        shl     rdi, 5
        xor     rdi, 0xaaaa
  	    and     rdi, 0x9999
        mov     rdi, 0xffff
        sub     rdi, 0xf000
        add     rdi, 0x1234
        shr     rdi, 5
        shl     rdi, 5
        xor     rdi, 0xaaaa
        and     rdi, 0x9999
        mov     rdi, 0xffff
        sub     rdi, 0xf000
        add     rdi, 0x1234
        mov     rdi, 0
        mov     rsi, 0
        mov     rdi, 1
        dec     rdi
        cmp     rdi, rsi
        je      then_case
        mov     rax, [rdi + rsi]
        jnz     main
        mov     rax, 0 ; We'll just exit with 0 (success).
        ret
.end:
